# Generated by Django 6.0 on 2025-12-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="ExpenseCost",
            new_name="EepenseCost",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="ExpenseDate",
            new_name="EpenseDate",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="ExpenseItem",
            new_name="EpenseItem",
        ),
    ]
