# Generated by Django 6.0 on 2025-12-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_rename_expensecost_expense_eepensecost_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="EepenseCost",
            new_name="ExpenseCost",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="EpenseDate",
            new_name="ExpenseDate",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="EpenseItem",
            new_name="ExpenseItem",
        ),
    ]
