# Generated by Django 6.0 on 2025-12-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0003_rename_eepensecost_expense_expensecost_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="UserDetail",
        ),
    ]
